[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install -g pnpm@latest",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
PNPM_HOME = "/pnpm"
PATH = "$PNPM_HOME:$PATH" 